[tool.ruff]
include = ["*.py"]

line-length = 78
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101", # missing self annotations
    "ANN102", # missing cls annotations
    "ANN401", # Any type hints are disallowed
    "T201",   # debug use of print
    # related to FIX and TODO
    "FIX",
    "TD002",
    "TD003",
    "SLF001", # private member access
    "PGH003", # type: ignore
    "D",      # missing documentation
    "RUF012", # missing ClassVar annotation
    "EXE001", # shebang is not executable
]

[tool.mypy]
files = ["server/**"]

python_version = "3.12"
platform = "linux"

plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "server.settings"
