# Generated by Django 5.0.6 on 2024-06-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("artist", models.CharField(max_length=150)),
                ("audio", models.FileField(upload_to="audio/")),
            ],
        ),
    ]
