# Generated by Django 4.2.13 on 2024-06-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracks", "0002_track_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
