# Generated by Django 4.2.13 on 2024-06-13 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("tracks", "0003_alter_track_uploader"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="track",
            name="date_last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="track",
            name="date_uploaded",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
